output "cloudformation_stack_name" {
  description = "The name of the AWS CloudFormation stack"
  value       = length(aws_cloudformation_stack.default) > 0 ? aws_cloudformation_stack.default[0].name : null
}

output "cloudformation_stack_id" {
  description = "The ID of the AWS CloudFormation stack"
  value       = length(aws_cloudformation_stack.default) > 0 ? aws_cloudformation_stack.default[0].id : null
}

output "cloudformation_stack_outputs" {
  description = "Outputs from the AWS CloudFormation stack"
  value       = length(aws_cloudformation_stack.default) > 0 ? aws_cloudformation_stack.default[0].outputs : {}
}

output "label_tags" {
  description = "Tags generated by the labels module"
  value       = module.labels.tags
}

output "label_name" {
  description = "The name label generated by the labels module"
  value       = module.labels.name
}

output "label_environment" {
  description = "The environment label generated by the labels module"
  value       = module.labels.environment
}

output "label_managedby" {
  description = "The managed by label extracted from tags"
  value       = try(module.labels.tags["managedby"], "ManagedBy label not found")
}