name: "Deploy Terraform cloudformation stacks"
permissions: write-all
on:
  workflow_dispatch:

jobs:
  control-tower:
    uses: clouddrove/github-shared-workflows/.github/workflows/terraform_workflow.yml@master
    with:
      provider: aws
      working_directory: 'terraform/control-tower/us-east-1/'
      aws_region: us-east-1
      approvers: vaibhav7797, pranaydeokar
      destroy: false
      timeout: 5
      terraform_version: 1.6.6
    secrets:
      BUILD_ROLE: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}